name: GoldenBridgeMobile
options:
  bundleIdPrefix: com.goldenbridge
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig
targets:
  GoldenBridgeMobile:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
        excludes:
          - "**/*.md"
    resources:
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.goldenbridge.mobile
        SWIFT_VERSION: 5.9
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  GoldenBridgeMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
    dependencies:
      - target: GoldenBridgeMobile
schemes:
  GoldenBridgeMobile:
    build:
      targets:
        GoldenBridgeMobile: all
        GoldenBridgeMobileTests: [test]
    test:
      targets:
        - name: GoldenBridgeMobileTests
          parallelizable: true
    run:
      environmentVariables:
        API_BASE_URL: $(API_BASE_URL)
        AUTH_BASE_URL: $(AUTH_BASE_URL)
